Added a CLI command to run an executable
UraniumTeam/actias pull request #44
Opened 2024-03-24 15:25 UTC by MaiNoTee

Fixes #40

2024-03-27 17:15 UTC, n-dub requested changes
Already discussed what to change

2024-04-01 17:18 UTC, n-dub requested changes

2024-04-01 17:18 UTC, n-dub commented on ActiasRuntimeTools/main.cpp
> +void build(const String& executable, int& result)
Имя надо писать с заглавной буквы, к тому же, если объявить ещё где-нибудь такую функцию `build`, будет ошибка линковщика. Надо сделать её `static`, чтобы она не была видна в других юнитах компиляции.

2024-04-01 17:18 UTC, n-dub commented on ActiasRuntimeTools/main.cpp
> +    auto ExecutableRead = File::ReadAllBytes(executable);
```suggestion
    auto executableRead = File::ReadAllBytes(executable);
```
Возможно `const`, хотя не уверен, что будет компилироваться.

2024-04-01 17:18 UTC, n-dub commented on ActiasRuntimeTools/main.cpp
> +        return;
А зачем? Почему бы просто не вернуть `return 1;`

2024-04-01 17:18 UTC, n-dub commented on ActiasRuntimeTools/main.cpp
> +    }
А тут `return 0;` в конце, так как ошибок нет.

2024-04-01 17:18 UTC, n-dub commented on ActiasRuntimeTools/main.cpp
> +            LibraryLoader loader(executableName, false);
Давай при объявлении переменных таким образом будем использовать фигурные скобки:
```suggestion
            LibraryLoader loader{executableName, false};
```
Иначе, если так вызвать дефолтный конструктор какого-нибудь класса, компилятор посчитает это за объявление функции, например:
```cpp
struct Foo
{
    Foo() { /* ... */ }
};

Foo foo(); // <-- объявилась локальная функция, возвращающая Foo
Foo foo{}; // <-- локальная переменная типа Foo, инициализированная
           //     дефолтным конструктором
```

2024-04-01 17:18 UTC, n-dub commented on ActiasRuntimeTools/main.cpp
> +            ActiasResult runResult = reinterpret_cast<ActiasResult (*)()>(mainFunc)();
Где можно `const`, везде `const`.

2024-04-01 17:18 UTC, n-dub commented on ActiasRuntimeTools/main.cpp
> +                return EXIT_FAILURE;
То, что ты возвращаешь из этой лямбды, скорее всего игнорируется библиотекой.
```suggestion
                return;
```

2024-04-01 17:18 UTC, n-dub commented on ActiasRuntimeTools/main.cpp
> +                return EXIT_FAILURE;
А вот вместо 1 можно прописать `EXIT_FAILURE` для читаемости.

2024-04-01 17:18 UTC, n-dub commented on ActiasRuntimeTools/main.cpp
> +            LibraryLoader loader(executableName, true);
```suggestion
            LibraryLoader loader{executableName, true};
```

2024-04-01 17:18 UTC, n-dub commented on ActiasRuntimeTools/main.cpp
> +                std::cerr << "Failed to run ACBX executable." << std::endl;
Не надо тут выводить ошибку, это же просто `main()` функция запущеной программы вернула код ошибки, так что не наши проблемы. Просто вернём потом `result = 1` из нашей программы.

2024-04-01 17:18 UTC, n-dub commented on ActiasRuntimeTools/main.cpp
> +        return EXIT_SUCCESS;
Это не надо вообще, мы из лямбды `void` возвращаем.

2024-04-03 15:48 UTC, MaiNoTee commented on ActiasRuntimeTools/main.cpp
> +    auto ExecutableRead = File::ReadAllBytes(executable);
Компилируется

2024-04-04 16:56 UTC, n-dub commented
Оно работает, ты проверял?

2024-04-04 16:56 UTC, n-dub approved these changes

2024-04-04 17:26 UTC, n-dub commented
не работает, хотя много чего пофиксил, но там почему-то крашит код в самом HelloActias

2024-04-04 17:27 UTC, n-dub commented
Хотя нет, он работает! Однако крашит после вывода "Hello, World"

2024-04-04 17:34 UTC, merged